version: "3.8"

volumes:
  postgres-data:

services:
  pgweb:
    container_name: pgweb
    restart: on-failure
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:root@db:5432/postgres?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: web_chat_api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - db

  web:
    image: web_chat_web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
    stdin_open: true
