version: "3.8"

volumes:
  postgres-data:

services:
  pgweb:
    container_name: pgweb
    restart: on-failure
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:root@db:5432/postgres?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data